---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: policyfile_zero
  require_chef_omnibus: 12.0.0-rc.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[::default]
    attributes:
